import {
  Injectable,
  signal,
  inject,
  PLATFORM_ID,
  EffectRef,
  effect,
  computed,
} from '@angular/core';
import { DOCUMENT, isPlatformBrowser } from '@angular/common';

export type Language = 'en' | 'ar';

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  private document = inject(DOCUMENT);
  private platformId = inject(PLATFORM_ID);

  currentLang = signal<Language>('en');

  // Translation Dictionary
  private translations: Record<Language, any> = {
    en: {
      // Layout
      admin: 'Admin',
      headOffice: 'Head Office',
      dashboard: 'Dashboard',
      branches: 'Branches',
      employees: 'Employees',
      services: 'Services',
      bookings: 'Bookings',
      orders: 'Orders',
      users: 'Users',
      analytics: 'Analytics',
      branchManager: 'Branch Manager',
      branchOverview: 'Branch Overview',
      queueSystem: 'Queue System',
      exit: 'Exit',

      // Common
      exportReport: 'Export Report',
      quickActions: 'Quick Actions',
      export: 'Export',
      back: 'Back',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      confirm: 'Confirm',
      actions: 'Actions',
      status: 'Status',
      name: 'Name',
      phone: 'Phone',
      role: 'Role',
      branch: 'Branch',
      rating: 'Rating',
      save: 'Save',
      update: 'Update',
      create: 'Create',
      search: 'Search',
      filterByName: 'Filter by name...',
      choosePhoto: 'Choose Photo',
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      selectBranch: 'Select a branch',
      loading: 'Loading...',
      noDataFound: 'No data found',

      // Admin - Users
      usersManagement: 'Users Management',
      viewManageUsers: 'View and manage all system users',
      allUsers: 'All Users',
      noUsersFound: 'No users found.',
      email: 'Email',
      roles: 'Roles',

      // Admin - Orders
      ordersManagement: 'Orders Management',
      viewManageOrders: 'View and manage all product orders',
      allOrders: 'All Orders',
      noOrdersFound: 'No orders found.',
      orderDetails: 'Order Details',
      customerInformation: 'Customer Information',
      orderItems: 'Order Items',
      qty: 'Qty',
      quantity: 'Quantity',
      paymentMethod: 'Payment Method',
      close: 'Close',
      address: 'Address',
      customer: 'Customer',
      date: 'Date',

      // Admin - Bookings
      viewManageBookings: 'View and manage all bookings across branches',
      noBookingsFound: 'No bookings found for this branch.',
      newBooking: 'New Booking',
      service: 'Service',
      barber: 'Barber',
      dateTime: 'Date & Time',
      complete: 'Complete',
      recentBookings: 'Recent Bookings',
      id: 'ID',
      searchBookingId: 'Search by Booking ID...',

      // Admin - Branches
      branchesManagement: 'Branches Management',
      manageLocations: 'Manage all your barber shop locations',
      addBranch: 'Add Branch',
      totalBranches: 'Total Branches',
      active: 'Active',
      inactive: 'Inactive',
      allBranches: 'All Branches',
      branchName: 'Branch Name',
      location: 'Location',
      manager: 'Manager',
      staff: 'Staff',
      revenue: 'Revenue',
      branchPhoto: 'Branch Photo',
      selectManager: 'Select Manager',

      // Admin - Services
      servicesManagement: 'Services Management',
      manageServices: 'Manage all services offered',
      addService: 'Add Service',
      totalServices: 'Total Services',
      allServices: 'All Services',
      serviceName: 'Service Name',
      duration: 'Duration',
      minutes: 'Minutes',

      // Admin - Products
      productsManagement: 'Products Management',
      manageProducts: 'Manage all products in inventory',
      totalProducts: 'Total Products',
      allProducts: 'All Products',

      // Hairstyle Recommender
      tryHaircut: 'Try Haircut',
      hairstyleRecommender: 'AI Hairstyle Recommender',
      hairstyleSubtitle:
        'Upload your photo and discover your next look with professional barber insights.',
      uploadPhoto: 'Upload Photo',
      dragDropWrapper: 'Drag & drop or click to browse',
      changePhoto: 'Change Photo',
      selectHairstyle: 'Select Hairstyle',
      generateNewLook: 'Generate New Look',
      processing: 'Processing...',
      yourNewLook: 'Your New Look',
      barberNote: "Barber's Note",
      validImageError: 'Please upload a valid image file.',
      uploadFirstError: 'Please upload an image first.',
      failedToGenerate: 'Failed to generate hairstyle',
      loginToUseAI: 'Please login to use the AI Hairstyle Recommender',
      loginNow: 'Login Now',

      // Dashboard
      superAdminDashboard: 'Sharks Dashboard',
      welcomeMessage: "Welcome back! Here's what's happening today.",
      totalRevenueYTD: 'Total Revenue (YTD)',
      yearToDateEarnings: 'Year to date earnings',
      totalBookings: 'Total Bookings',
      allTimeBookings: 'All time bookings',
      activeBranches: 'Active Branches',
      operationalLocations: 'Operational locations',
      avgWaitTime: 'Avg Wait Time',
      minutesPerCustomer: 'Minutes per customer',
      dailyRevenue: 'Daily Revenue',
      weeklyRevenue: 'Weekly Revenue',
      monthlyRevenue: 'Monthly Revenue',
      completedBookings: 'Completed Bookings',
      revenueTrends: 'Revenue Trends',
      revenueByBranch: 'Revenue by Branch',
      revenueByService: 'Revenue by Service',
      topPerformingBarbers: 'Top Performing Barbers',
      customerBreakdown: 'Customer Breakdown',
      revenueByTimeOfDay: 'Revenue by Time of Day',
      newCustomers: 'New Customers',
      returningCustomers: 'Returning Customers',
      cancelledBookings: 'Cancelled Bookings',
      averageRating: 'Average Rating',

      // Employees
      employeesManagement: 'Employees Management',
      manageStaff: 'Manage barbers and staff across all branches',
      addEmployee: 'Add Employee',
      totalEmployees: 'Total Employees',
      activeToday: 'Active Today',
      onLeave: 'On Leave',
      avgPerformance: 'Avg Performance',
      allEmployees: 'All Employees',
      noEmployeesFound: 'No employees found matching',
      employeePhoto: 'Employee Photo',
      editEmployee: 'Edit Employee',
      addNewEmployee: 'Add New Employee',

      // Store
      store: 'Store',
      products: 'Products',
      addToCart: 'Add to Cart',
      price: 'Price',
      currency: 'LE',
      productDetails: 'Product Details',
      category: 'Category',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      buyNow: 'Buy Now',
      cart: 'Cart',
      items: 'Items',
      total: 'Total',
      checkout: 'Checkout',
      shoppingCart: 'Shopping Cart',
      emptyCart: 'Your cart is empty',
      continueShopping: 'Continue Shopping',
      addedToCart: 'Added to cart!',

      // Product Management
      addProduct: 'Add Product',
      editProduct: 'Edit Product',
      deleteProduct: 'Delete Product',
      productName: 'Product Name',
      description: 'Description',
      stock: 'Stock',
      image: 'Image',

      // Landing Page
      premiumBarberExperience: 'Premium Barber Experience',
      experienceArt: 'Experience the Art of',
      masterfulGrooming: 'Masterful Grooming',
      heroSubtitle:
        'Where traditional craftsmanship meets modern style. Elevate your look with our expert barbers in an atmosphere of refined luxury.',
      bookAppointment: 'Book Appointment',
      exploreServices: 'Explore Services',
      // averageRating key exists in Dashboard section
      happyClients: 'Happy Clients',
      yearsExperience: 'Years Experience',
      whyChoose: 'Why Choose Sharks?',
      whyChooseSubtitle:
        'We combine traditional techniques with modern style to give you the best look.',
      expertBarbers: 'Expert Barbers',
      expertBarbersDesc:
        'Our team consists of highly trained professionals with years of experience.',
      premiumComfort: 'Premium Comfort',
      premiumComfortDesc:
        'Relax in our luxury chairs and enjoy a complimentary beverage with every cut.',
      easyBooking: 'Easy Booking',
      easyBookingDesc: 'Book your appointment online in seconds. Choose your barber and time slot.',
      popularBranches: 'Popular Branches',
      findLocation: 'Find a location near you.',
      viewAll: 'View All',
      open: 'Open',
      closed: 'Closed',
      book: 'Book',

      // Main Layout
      home: 'Home',
      myBookings: 'My Bookings',
      signIn: 'Sign In',
      footerTagline: 'Premium grooming services for the modern gentleman.',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      support: 'Support',
      contactUs: 'Contact Us',
      faq: 'FAQ',
      privacyPolicy: 'Privacy Policy',
      connect: 'Connect',
      rightsReserved: 'All rights reserved.',
      findBranch: 'Find a Branch',
      searchPlaceholder: 'Search by name or location...',
      viewDetails: 'View Details',
      noBranchesFound: 'No branches found matching your search.',

      // Client - History
      myHistory: 'My History',
      loadingBookings: 'Loading bookings...',
      noBookingsYet: 'You have no bookings yet',
      serialCode: 'Serial Code',
      notSpecified: 'Not Specified',
      amount: 'Amount',
      loadingOrders: 'Loading orders...',
      noOrdersYet: 'You have no orders yet',
      orderNumber: 'Order',

      // Client - Profile
      security: 'Security',
      personalDetails: 'Personal Details',
      updateAccountInfo: 'Update your account information.',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      phoneNumberLabel: 'Phone Number',
      saving: 'Saving...',
      changePassword: 'Change Password',
      updatePasswordInfo: 'Update your password to keep your account secure.',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      passwordsDoNotMatch: 'Passwords do not match',
      updating: 'Updating...',
      updatePassword: 'Update Password',
      permanentDeleteWarning: 'Permanently remove your account and data.',
      myAccount: 'my account',
      profileUpdatedSuccess: 'Profile updated successfully',
      passwordChangedSuccess: 'Password changed successfully',
      accountDeletedSuccess: 'Account deleted successfully',
      deleteFailed: 'Failed to delete account',
      updateProfileFailed: 'Failed to update profile',
      changePasswordFailed: 'Failed to change password. check your current password',
      userIdNotFound: 'User ID not found',
      error: 'Error',
      success: 'Success',

      // Client - Register
      passwordRequirementsTitle: 'Password must contain:',
      reqMinLength: 'At least 6 characters',
      reqUppercase: 'Uppercase letter',
      reqLowercase: 'Lowercase letter',
      reqNumber: 'Number',
      reqSpecial: 'Special character',
      registrationFailed: 'Registration Failed',
      tryAgain: 'Please try again.',
      weakPassword: 'Weak Password',
      passwordRequirementsError: 'Please ensure your password meets all requirements.',
      invalidForm: 'Invalid Form',
      fillRequiredFields: 'Please fill in all required fields correctly.',

      // Client - Cart

      cartEmpty: 'Your cart is empty',
      addProductsMsg: 'Add some products to get started!',

      clearCart: 'Clear Cart',
      remove: 'Remove',
      orderSummary: 'Order Summary',
      shippingAddress: 'Shipping Address',
      scAddressPlaceholder: 'Street, Building, Apartment...',
      subtotal: 'Subtotal',
      itemsCount: 'items',

      proceedToCheckout: 'Proceed to Checkout',
      confirmRemoveItem: 'Remove this item from cart?',
      confirmClearCart: 'Are you sure you want to clear your cart?',

      // Client - Checkout
      checkoutTitle: 'Checkout',
      shippingDetails: 'Shipping Details',

      totalAmount: 'Total Amount',
      paymentTitle: 'Payment',
      payPal: 'PayPal',
      creditDebitCard: 'Credit / Debit Card',
      cashOnDelivery: 'Cash on Delivery',
      payWhenReceived: 'Pay when received',
      processingPayment: 'Processing payment...',
      placeOrder: 'Place Order',
      confirmOrderTitle: 'Confirm Order',
      confirmOrderMsg: 'Are you sure you want to place this order with Cash on Delivery?',
      confirmOrderBtn: 'Confirm Order',

      paymentFailed: 'Payment failed. Please try again.',
      paymentSuccess: 'Payment successful! Order placed.',
      orderPlacedSuccess: 'Order placed successfully! Pay cash on delivery.',
      orderError: 'Error saving your order. Please contact support.',

      // Booking Flow
      stepService: 'Service',
      stepDateTime: 'Date & Time',
      stepBarber: 'Barber',
      stepPayment: 'Payment',
      stepConfirm: 'Confirm',

      selectServiceTitle: 'Select a Service',
      loadingServices: 'Loading services...',
      nextDateTime: 'Next: Date & Time',

      selectDateTimeTitle: 'Select Date & Time',
      dateLabel: 'Date',
      selectTimeLabel: 'Select Time',
      nextDay: '(Next Day)',
      nextBarber: 'Next: Select Barber',

      selectBarberTitle: 'Select Barber (Optional)',
      anyProfessional: 'Any Professional',
      firstAvailableBarber: 'First available barber',
      nextPayment: 'Next: Payment',

      paymentMethodTitle: 'Payment Method',
      payCashTitle: 'Pay Cash on Arrival',
      payCashDesc: 'Pay at the counter',
      payPalTitle: 'PayPal',
      payPalDesc: 'Secure online payment',
      bookingSummary: 'Booking Summary',
      serviceLabel: 'Service',
      dateTimeLabel: 'Date & Time',
      at: 'at',
      totalLabel: 'Total',
      bookBtn: 'Book',

      bookingConfirmedTitle: 'Booking Confirmed!',
      bookingConfirmedDesc:
        "Your appointment has been successfully booked. We've sent a confirmation email to your inbox.",
      appointmentDetails: 'Appointment Details',
      timeLabel: 'Time',
      barberLabel: 'Barber',
      paymentLabel: 'Payment',
      backToHome: 'Back to Home',
      viewMyBookings: 'View My Bookings',

      // FAQ
      faqTitle: 'Frequently Asked Questions',
      faqSubtitle: "Everything you need to know about Shark's Barber Shop.",
      q1: 'What are your working hours?',
      a1: 'We are open every day from 10:00 AM to 12:00 AM.',
      q2: 'Do I need an appointment?',
      a2: 'Walk-ins are welcome, but we recommend booking an appointment to avoid waiting.',
      q3: 'Where are you located?',
      a3: 'We have two branches in Beni Suef: East Nile (City Center) and Corniche El Nil.',
      q4: 'What services do you offer?',
      a4: 'We offer haircuts, beard grooming, styling, facials, and grooming packages.',
      q5: 'Can I choose my barber?',
      a5: 'Yes! You can choose your preferred barber when booking online or visiting us.',

      // Contact
      contactTitle: 'Get in Touch',
      contactSubtitle: 'Have questions? We are here to help.',
      ourBranches: 'Our Branches',
      cleanliness: 'Cleanliness',
      precision: 'Precision',
      style: 'Style',
      branch1Name: 'East Nile Branch',
      branch1Address: 'City Center, behind Despacito, next to Caviar - New Beni Suef',
      branch2Name: 'Corniche Branch',
      branch2Address: 'Corniche El Nil, next to Health Insurance',
      callUs: 'Call Us',
      followUs: 'Follow Us',
      slogan: "Shark's - Where Details Matter",
      facebookPage: 'Facebook Page',

      // Auth
      signInTitle: 'Sign in to your account',
      or: 'Or',
      createNewAccount: 'create a new account',
      emailLabel: 'Email address',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot your password?',
      signInButton: 'Sign in',
      orContinueWith: 'Or continue with',
      signInWithGoogle: 'Sign in with Google',
      registerTitle: 'Create a new account',
      signInToExisting: 'sign in to existing account',
      fullNameLabel: 'Full Name',
      confirmPasswordLabel: 'Confirm Password',
      createAccountButton: 'Create Account',
      hello: 'Hello',
      profile: 'Profile',
      logout: 'Logout',
      accountSettings: 'Account Settings',
      saveChanges: 'Save Changes',
      dangerZone: 'Danger Zone',
      deleteAccount: 'Delete Account',

      // Branch Panel - Queue
      chairs: 'Chairs',
      activeChairs: 'Active',
      noBarber: 'No Barber',
      free: 'Free',
      occupied: 'Occupied',
      waitingQueue: 'Waiting Queue',
      waiting: 'Waiting',
      pref: 'Pref',
      assign: 'Assign',
      queueEmpty: 'Queue is empty',
      liveQueueDisplay: 'Live Queue Display',
      openLiveQueue: 'Open Live Queue',
      refresh: 'Refresh',
      addNewChair: '+ Add New Chair',
      cancelAdd: 'Cancel',
      chairName: 'Chair Name',
      assignedBarber: 'Assigned Barber',
      searchBarberName: 'Search Barber Name...',
      noBarbersFound: 'No barbers found',
      walkInBooking: 'Walk-in Booking',
      firstName: 'First Name',
      lastName: 'Last Name',
      selectService: 'Select Service',
      createWalkIn: 'Create Walk-in Booking',
      manualEnqueue: 'Manual Enqueue',
      bookingId: 'Booking ID',
      priority: 'Priority',
      addToQueue: 'Add to Queue',
      assignCustomer: 'Assign Customer',
      selectChairToAssign: 'Select a chair to assign this booking to:',

      // Surveys
      downloadQrCode: 'Download QR Code',
      feedbackLink: 'Feedback Link',
      customerFeedbackLink: 'Customer Feedback Link',
      shareLinkDesc: 'Share this link with customers to collect star ratings for your branch.',
      surveysFeedback: 'Surveys & Feedback',
      copy: 'Copy',
      copied: 'Copied!',
      qrCode: 'QR Code',
    },
    ar: {
      // Layout
      admin: 'الإدارة',
      headOffice: 'المكتب الرئيسي',
      dashboard: 'لوحة التحكم',
      branches: 'الفروع',
      employees: 'الموظفين',
      services: 'الخدمات',
      bookings: 'الحجوزات',
      orders: 'الطلبات',
      users: 'المستخدمين',
      analytics: 'التحليلات',
      branchManager: 'مدير الفرع',
      branchOverview: 'نظرة عامة للفرع',
      queueSystem: 'نظام الطابور',
      exit: 'خروج',

      // Common
      exportReport: 'تصدير التقرير',
      quickActions: 'إجراءات سريعة',
      export: 'تصدير',
      back: 'رجوع',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      view: 'عرض',
      confirm: 'تأكيد',
      actions: 'إجراءات',
      status: 'الحالة',
      name: 'الاسم',
      phone: 'الهاتف',
      role: 'الوظيفة',
      branch: 'الفرع',
      rating: 'التقييم',
      save: 'حفظ',
      update: 'تحديث',
      create: 'إنشاء',
      search: 'بحث',
      filterByName: 'بحث بالاسم...',
      choosePhoto: 'اختر صورة',
      fullName: 'الاسم الكامل',
      phoneNumber: 'رقم الهاتف',
      selectBranch: 'اختر فرع',
      loading: 'جاري التحميل...',
      noDataFound: 'لا توجد بيانات',

      // Admin - Users
      usersManagement: 'إدارة المستخدمين',
      viewManageUsers: 'عرض وإدارة جميع مستخدمي النظام',
      allUsers: 'جميع المستخدمين',
      noUsersFound: 'لم يتم العثور على مستخدمين.',
      email: 'البريد الإلكتروني',
      roles: 'الأدوار',

      // Admin - Orders
      ordersManagement: 'إدارة الطلبات',
      viewManageOrders: 'عرض وإدارة جميع طلبات المنتجات',
      allOrders: 'جميع الطلبات',
      noOrdersFound: 'لم يتم العثور على طلبات.',
      orderDetails: 'تفاصيل الطلب',
      customerInformation: 'معلومات العميل',
      orderItems: 'عناصر الطلب',
      qty: 'الكمية',
      quantity: 'الكمية',
      paymentMethod: 'طريقة الدفع',
      close: 'إغلاق',
      address: 'العنوان',
      customer: 'العميل',
      date: 'التاريخ',

      // Admin - Bookings
      viewManageBookings: 'عرض وإدارة جميع الحجوزات عبر الفروع',
      noBookingsFound: 'لم يتم العثور على حجوزات لهذا الفرع.',
      newBooking: 'حجز جديد',
      service: 'الخدمة',
      barber: 'الحلاق',
      dateTime: 'التاريخ والوقت',
      complete: 'إكمال',
      recentBookings: 'أحدث الحجوزات',
      id: 'المعرف',
      searchBookingId: 'بحث برقم الحجز...',

      // Admin - Branches
      branchesManagement: 'إدارة الفروع',
      manageLocations: 'إدارة جميع مواقع صالونات الحلاقة',
      addBranch: 'إضافة فرع',
      totalBranches: 'إجمالي الفروع',
      active: 'نشط',
      inactive: 'غير نشط',
      allBranches: 'جميع الفروع',
      branchName: 'اسم الفرع',
      location: 'الموقع',
      manager: 'المدير',
      staff: 'الموظفون',
      revenue: 'الإيرادات',
      branchPhoto: 'صورة الفرع',
      selectManager: 'اختر مدير',

      // Admin - Services
      servicesManagement: 'إدارة الخدمات',
      manageServices: 'إدارة جميع الخدمات المقدمة',
      addService: 'إضافة خدمة',
      totalServices: 'إجمالي الخدمات',
      allServices: 'جميع الخدمات',
      serviceName: 'اسم الخدمة',
      duration: 'المدة',
      minutes: 'دقائق',

      // Admin - Products
      productsManagement: 'إدارة المنتجات',
      manageProducts: 'إدارة جميع المنتجات في المخزون',
      totalProducts: 'إجمالي المنتجات',
      allProducts: 'جميع المنتجات',

      // Hairstyle Recommender
      tryHaircut: 'جرب قصة الشعر',
      hairstyleRecommender: 'مستشار قصات الشعر بالذكاء الاصطناعي',
      hairstyleSubtitle: 'ارفع صورتك واكتشف مظهرك الجديد مع نصائح حلاقة احترافية.',
      uploadPhoto: 'رفع صورة',
      dragDropWrapper: 'اسحب وأفلت أو انقر للتصفح',
      changePhoto: 'تغيير الصورة',
      selectHairstyle: 'اختر قصة الشعر',
      generateNewLook: 'إنشاء مظهر جديد',
      processing: 'جاري المعالجة...',
      yourNewLook: 'مظهرك الجديد',
      barberNote: 'ملاحظة الحلاق',
      validImageError: 'يرجى رفع ملف صورة صالح.',
      uploadFirstError: 'يرجى رفع صورة أولاً.',
      failedToGenerate: 'فشل إنشاء قصة الشعر',
      loginToUseAI: 'يرجى تسجيل الدخول لاستخدام مستشار قصات الشعر بالذكاء الاصطناعي',
      loginNow: 'سجل دخول الآن',

      // Dashboard
      superAdminDashboard: 'لوحة تحكم Sharks',
      welcomeMessage: 'مرحباً بعودتك! إليك ملخص اليوم.',
      totalRevenueYTD: 'إجمالي الإيرادات (السنة الحالية)',
      yearToDateEarnings: 'أرباح منذ بداية العام',
      totalBookings: 'إجمالي الحجوزات',
      allTimeBookings: 'جميع الحجوزات',
      activeBranches: 'الفروع النشطة',
      operationalLocations: 'المواقع العاملة',
      avgWaitTime: 'متوسط وقت الانتظار',
      minutesPerCustomer: 'دقيقة لكل عميل',
      dailyRevenue: 'الإيرادات اليومية',
      weeklyRevenue: 'الإيرادات الأسبوعية',
      monthlyRevenue: 'الإيرادات الشهرية',
      completedBookings: 'الحجوزات المكتملة',
      revenueTrends: 'اتجاهات الإيرادات',
      revenueByBranch: 'الإيرادات حسب الفرع',
      revenueByService: 'الإيرادات حسب الخدمة',
      topPerformingBarbers: 'أفضل الحلاقين أداءً',
      customerBreakdown: 'توزيع العملاء',
      revenueByTimeOfDay: 'الإيرادات حسب الوقت',
      newCustomers: 'عملاء جدد',
      returningCustomers: 'عملاء عائدون',
      cancelledBookings: 'حجوزات ملغاة',
      averageRating: 'متوسط التقييم',

      // Employees
      employeesManagement: 'إدارة الموظفين',
      manageStaff: 'إدارة الحلاقين والموظفين في جميع الفروع',
      addEmployee: 'إضافة موظف',
      totalEmployees: 'إجمالي الموظفين',
      activeToday: 'نشط اليوم',
      onLeave: 'في إجازة',
      avgPerformance: 'متوسط الأداء',
      allEmployees: 'جميع الموظفين',
      noEmployeesFound: 'لا يوجد موظفين مطابقين لـ',
      employeePhoto: 'صورة الموظف',
      editEmployee: 'تعديل موظف',
      addNewEmployee: 'إضافة موظف جديد',

      // Store
      store: 'المتجر',
      products: 'المنتجات',
      addToCart: 'أضف إلى السلة',
      price: 'السعر',
      currency: 'ج.م',
      productDetails: 'تفاصيل المنتج',
      category: 'الفئة',
      inStock: 'متوفر',
      outOfStock: 'غير متوفر',
      buyNow: 'شراء الآن',
      cart: 'السلة',
      items: 'عناصر',
      total: 'الإجمالي',
      checkout: 'الدفع',
      shoppingCart: 'سلة التسوق',
      emptyCart: 'سلتك فارغة',
      continueShopping: 'متابعة التسوق',
      addedToCart: 'تمت الإضافة للسلة!',

      // Product Management
      addProduct: 'إضافة منتج',
      editProduct: 'تعديل منتج',
      deleteProduct: 'حذف منتج',
      productName: 'اسم المنتج',
      description: 'الوصف',
      stock: 'المخزون',
      image: 'الصورة',

      // Landing Page
      premiumBarberExperience: 'تجربة حلاقة فاخرة',
      experienceArt: 'جرب فن',
      masterfulGrooming: 'الحلاقة المتقنة',
      heroSubtitle:
        'حيث تلتقي الحرفية التقليدية بالأسلوب الحديث. ارتقِ بمظهرك مع خبرائنا في أجواء من الفخامة الراقية.',
      bookAppointment: 'احجز موعداً',
      exploreServices: 'استكشف الخدمات',
      // averageRating key exists in Dashboard section
      happyClients: 'عميل سعيد',
      yearsExperience: 'سنوات خبرة',
      whyChoose: 'لماذا تختار Sharks',
      whyChooseSubtitle: 'نجمع بين التقنيات التقليدية والأسلوب الحديث لمنحك أفضل مظهر.',
      expertBarbers: 'حلاقون خبراء',
      expertBarbersDesc: 'فريقنا يتكون من محترفين مدربين تدريباً عالياً ولديهم سنوات من الخبرة.',
      premiumComfort: 'راحة فاخرة',
      premiumComfortDesc: 'استرخ في مقاعدنا الفاخرة واستمتع بمشروب مجاني مع كل قصة شعر.',
      easyBooking: 'حجز سهل',
      easyBookingDesc: 'احجز موعدك عبر الإنترنت في ثوان. اختر حلاقك والوقت المناسب.',
      popularBranches: 'الفروع الشهيرة',
      findLocation: 'ابحث عن موقع قريب منك.',
      viewAll: 'عرض الكل',
      open: 'مفتوح',
      closed: 'مغلق',
      book: 'حجز',

      // Main Layout
      home: 'الرئيسية',
      myBookings: 'حجوزاتي',
      signIn: 'تسجيل الدخول',
      footerTagline: 'خدمات حلاقة فاخرة للرجل العصري.',
      quickLinks: 'روابط سريعة',
      aboutUs: 'من نحن',
      support: 'الدعم',
      contactUs: 'اتصل بنا',
      faq: 'الأسئلة الشائعة',
      privacyPolicy: 'سياسة الخصوصية',
      connect: 'تواصل معنا',
      rightsReserved: 'جميع الحقوق محفوظة.',
      findBranch: 'ابحث عن فرع',
      searchPlaceholder: 'ابحث بالاسم أو الموقع...',
      viewDetails: 'عرض التفاصيل',
      noBranchesFound: 'لا توجد فروع تطابق بحثك.',

      // Client - History
      myHistory: 'سجلي',
      loadingBookings: 'جاري تحميل الحجوزات...',
      noBookingsYet: 'ليس لديك حجوزات حتى الآن',
      serialCode: 'كود التسلسل',
      notSpecified: 'غير محدد',
      amount: 'المبلغ',
      loadingOrders: 'جاري تحميل الطلبات...',
      noOrdersYet: 'ليس لديك طلبات حتى الآن',
      orderNumber: 'طلب',

      // Client - Profile
      security: 'الأمان',
      personalDetails: 'تفاصيل شخصية',
      updateAccountInfo: 'تحديث معلومات حسابك.',
      firstNameLabel: 'الاسم الأول',
      lastNameLabel: 'الاسم العائلة',
      phoneNumberLabel: 'رقم الهاتف',
      saving: 'جاري الحفظ...',
      changePassword: 'تغيير كلمة المرور',
      updatePasswordInfo: 'تحديث كلمة المرور للحفاظ على أمان حسابك.',
      currentPassword: 'كلمة المرور الحالية',
      newPassword: 'كلمة المرور الجديدة',
      confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
      passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
      updating: 'جاري التحديث...',
      updatePassword: 'تحديث كلمة المرور',
      permanentDeleteWarning: 'حذف حسابك وبياناتك نهائياً.',
      myAccount: 'حسابي',
      profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح',
      passwordChangedSuccess: 'تم تغيير كلمة المرور بنجاح',
      accountDeletedSuccess: 'تم حذف الحساب بنجاح',
      deleteFailed: 'فشل حذف الحساب',
      updateProfileFailed: 'فشل تحديث الملف الشخصي',
      changePasswordFailed: 'فشل تغيير كلمة المرور. تحقق من كلمة المرور الحالية',
      userIdNotFound: 'لم يتم العثور على معرف المستخدم',
      error: 'خطأ',
      success: 'نجاح',

      // Client - Register
      passwordRequirementsTitle: 'يجب أن تحتوي كلمة المرور على:',
      reqMinLength: '6 أحرف على الأقل',
      reqUppercase: 'حرف كبير',
      reqLowercase: 'حرف صغير',
      reqNumber: 'رقم',
      reqSpecial: 'رمز خاص',
      registrationFailed: 'فشل التسجيل',
      tryAgain: 'الرجاء المحاولة مرة أخرى.',
      weakPassword: 'كلمة مرور ضعيفة',
      passwordRequirementsError: 'يرجى التأكد من استيفاء كلمة المرور لجميع المتطلبات.',
      invalidForm: 'نموذج غير صالح',
      fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة بشكل صحيح.',

      // Client - Cart

      cartEmpty: 'سلة التسوق فارغة',
      addProductsMsg: 'أضف بعض المنتجات للبدء!',

      clearCart: 'إفراغ السلة',
      remove: 'إزالة',
      orderSummary: 'ملخص الطلب',
      shippingAddress: 'عنوان الشحن',
      scAddressPlaceholder: 'الشارع، المبنى، الشقة...',
      subtotal: 'المجموع الفرعي',
      itemsCount: 'عناصر',

      proceedToCheckout: 'متابعة الدفع',
      confirmRemoveItem: 'هل تريد إزالة هذا العنصر من السلة؟',
      confirmClearCart: 'هل أنت متأكد أنك تريد إفراغ السلة؟',

      // Client - Checkout
      checkoutTitle: 'الدفع',
      shippingDetails: 'تفاصيل الشحن',

      totalAmount: 'المبلغ الإجمالي',
      paymentTitle: 'الدفع',
      payPal: 'باي بال (PayPal)',
      creditDebitCard: 'بطاقة ائتمان / خصم',
      cashOnDelivery: 'الدفع عند الاستلام',
      payWhenReceived: 'ادفع عند استلام الطلب',
      processingPayment: 'جاري معالجة الدفع...',
      placeOrder: 'تأكيد الطلب',
      confirmOrderTitle: 'تأكيد الطلب',
      confirmOrderMsg: 'هل أنت متأكد أنك تريد تأكيد هذا الطلب والدفع عند الاستلام؟',
      confirmOrderBtn: 'تأكيد الطلب',

      paymentFailed: 'فشل الدفع. الرجاء المحاولة مرة أخرى.',
      paymentSuccess: 'تم الدفع بنجاح! تم إنشاء الطلب.',
      orderPlacedSuccess: 'تم إنشاء الطلب بنجاح! الدفع عند الاستلام.',
      orderError: 'خطأ في حفظ طلبك. يرجى الاتصال بالدعم.',

      // Booking Flow
      stepService: 'الخدمة',
      stepDateTime: 'الوقت والتاريخ',
      stepBarber: 'الحلاق',
      stepPayment: 'الدفع',
      stepConfirm: 'تأكيد',

      selectServiceTitle: 'اختر خدمة',
      loadingServices: 'جاري تحميل الخدمات...',
      nextDateTime: 'التالي: التاريخ والوقت',

      selectDateTimeTitle: 'اختر التاريخ والوقت',
      dateLabel: 'التاريخ',
      selectTimeLabel: 'اختر الوقت',
      nextDay: '(اليوم التالي)',
      nextBarber: 'التالي: اختيار الحلاق',

      selectBarberTitle: 'اختر الحلاق (اختياري)',
      anyProfessional: 'أي محترف',
      firstAvailableBarber: 'أول حلاق متاح',
      nextPayment: 'التالي: الدفع',

      paymentMethodTitle: 'طريقة الدفع',
      payCashTitle: 'دفع نقدي عند الوصول',
      payCashDesc: 'الدفع عند الكاونتر',
      payPalTitle: 'باي بال (PayPal)',
      payPalDesc: 'دفع آمن عبر الإنترنت',
      bookingSummary: 'ملخص الحجز',
      serviceLabel: 'الخدمة',
      dateTimeLabel: 'التاريخ والوقت',
      at: 'في',
      totalLabel: 'الإجمالي',
      bookBtn: 'حجز',

      bookingConfirmedTitle: 'تم تأكيد الحجز!',
      bookingConfirmedDesc:
        'تم حجز موعدك بنجاح. لقد أرسلنا رسالة تأكيد إلكترونية إلى بريدك الوارد.',
      appointmentDetails: 'تفاصيل الموعد',
      timeLabel: 'الوقت',
      barberLabel: 'الحلاق',
      paymentLabel: 'الدفع',
      backToHome: 'العودة للرئيسية',
      viewMyBookings: 'عرض حجوزاتي',

      // FAQ
      faqTitle: 'الأسئلة الشائعة',
      faqSubtitle: 'كل ما تريد معرفته عن صالون شاركس.',
      q1: 'ما هي ساعات العمل؟',
      a1: 'نحن نعمل يومياً من الساعة 10:00 صباحاً حتى 12:00 منتصف الليل.',
      q2: 'هل أحتاج إلى حجز موعد؟',
      a2: 'نرحب بالزوار بدون حجز، لكن نوصي بحجز موعد لتجنب الانتظار.',
      q3: 'أين تقع فروعكم؟',
      a3: 'لدينا فرعين في بني سويف: شرق النيل (الحي الأول) وكورنيش النيل.',
      q4: 'ما هي الخدمات التي تقدمونها؟',
      a4: 'نقدم قصات شعر، حلاقة ذقن، تصفيف، تنظيف بشرة، وباقات العناية.',
      q5: 'هل يمكنني اختيار الحلاق؟',
      a5: 'نعم! يمكنك اختيار حلاقك المفضل عند الحجز عبر الموقع أو عند زيارتنا.',

      // Contact
      contactTitle: 'تواصل معنا',
      contactSubtitle: 'لديك استفسار؟ نحن هنا للمساعدة.',
      ourBranches: 'فروعنا',
      cleanliness: 'نظافة',
      precision: 'دقة',
      style: 'استايل',
      branch1Name: 'فرع شرق النيل',
      branch1Address: 'الحي الأول - خلف ديسباسيتو - بجوار كاڤيار - بني سويف الجديدة',
      branch2Name: 'فرع الكورنيش',
      branch2Address: 'كورنيش النيل بجوار التامين الصحي',
      callUs: 'اتصل بنا',
      followUs: 'تابعنا',
      slogan: 'شاركس - الروقان باين في كل المكان',
      facebookPage: 'صفحة الفيسبوك',

      // Auth
      signInTitle: 'تسجيل الدخول إلى حسابك',
      or: 'أو',
      createNewAccount: 'إنشاء حساب جديد',
      emailLabel: 'البريد الإلكتروني',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'كلمة المرور',
      passwordPlaceholder: '••••••••',
      rememberMe: 'تذكرني',
      forgotPassword: 'نسيت كلمة المرور؟',
      signInButton: 'تسجيل الدخول',
      orContinueWith: 'أو المتابعة باستخدام',
      signInWithGoogle: 'تسجيل الدخول عبر Google',
      registerTitle: 'إنشاء حساب جديد',
      signInToExisting: 'تسجيل الدخول لحساب موجود',
      fullNameLabel: 'الاسم الكامل',
      confirmPasswordLabel: 'تأكيد كلمة المرور',
      createAccountButton: 'إنشاء الحساب',
      hello: 'مرحباً',
      profile: 'الملف الشخصي',
      logout: 'تسجيل الخروج',
      accountSettings: 'إعدادات الحساب',
      saveChanges: 'حفظ التغييرات',
      dangerZone: 'منطقة الخطر',
      deleteAccount: 'حذف الحساب',

      // Branch Panel - Queue
      chairs: 'الكراسي',
      activeChairs: 'نشط',
      noBarber: 'لا يوجد حلاق',
      free: 'فارغ',
      occupied: 'مشغول',
      waitingQueue: 'قائمة الانتظار',
      waiting: 'انتظار',
      pref: 'تفضيل',
      assign: 'تعيين',
      queueEmpty: 'القائمة فارغة',
      liveQueueDisplay: 'شاشة الطابور المباشر',
      openLiveQueue: 'فتح الشاشة المباشرة',
      refresh: 'تحديث',
      addNewChair: 'إضافة كرسي جديد',
      cancelAdd: 'إلغاء',
      chairName: 'اسم الكرسي',
      assignedBarber: 'الحلاق المعين',
      searchBarberName: 'بحث عن اسم الحلاق...',
      noBarbersFound: 'لا يوجد حلاقين',
      walkInBooking: 'حجز فوري (Walk-in)',
      firstName: 'الاسم الأول',
      lastName: 'الاسم العائلة',
      selectService: 'اختر خدمة',
      createWalkIn: 'إنشاء حجز فوري',
      manualEnqueue: 'إضافة يدوية للطابور',
      bookingId: 'رقم الحجز',
      priority: 'الأولوية',
      addToQueue: 'إضافة للطابور',
      assignCustomer: 'تعيين عميل',
      selectChairToAssign: 'اختر كرسياً لتعيين الحجز له:',

      // Surveys
      downloadQrCode: 'تحميل رمز QR',
      feedbackLink: 'رابط الملاحظات',
      customerFeedbackLink: 'رابط ملاحظات العملاء',
      shareLinkDesc: 'شارك هذا الرابط مع العملاء لجمع التقييمات لفرعك.',
      surveysFeedback: 'الاستبيانات والملاحظات',
      copy: 'نسخ',
      copied: 'تم النسخ!',
      qrCode: 'رمز QR',
    },
  };

  // Computed signal for current translations
  t = computed<any>(() => this.translations[this.currentLang()]);

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      // Load saved language or default to 'en'
      const savedLang = localStorage.getItem('lang') as Language;
      if (savedLang) {
        this.setLanguage(savedLang);
      }
    }

    effect(() => {
      const lang = this.currentLang();
      if (isPlatformBrowser(this.platformId)) {
        localStorage.setItem('lang', lang);
        this.updateDocument(lang);
      }
    });
  }

  toggleLanguage() {
    this.setLanguage(this.currentLang() === 'en' ? 'ar' : 'en');
  }

  setLanguage(lang: Language) {
    this.currentLang.set(lang);
  }

  private updateDocument(lang: Language) {
    // const dir = lang === 'ar' ? 'rtl' : 'ltr';
    this.document.documentElement.lang = lang;
    // this.document.documentElement.dir = dir;
  }
}
